tbranyen/diffhtml

- .travis.yml
- README.md
- dist/diffhtml.js
- index.js
- package.json
- test/assert.js
- test/index.html
- test/test.diffhtml.js
Also updated the signature to be more robust.  Only supports Strings
now and any other types will be rejected.  This also allows passing an empty
top level string.
> Adds basic tests and Travis-CI integration

- .jshintrc
- dist/diffhtml.js
- lib/element/custom.js
- lib/element/make.js
- lib/errors.js
- lib/index.js
- lib/node/make.js
- lib/node/patch.js
- lib/node/sync.js
- lib/node/tree.js
- lib/patches/process.js
- lib/util/memory.js
- lib/util/parser.js
- lib/util/pools.js
- lib/util/uuid.js
- lib/worker/create.js
- test/index.html
- test/integration/custom.js
Contains the initial work on a custom elements implementation that roughly follows the Web Components specification. We will deviate where necessary, as the specification is currently far from complete.
> Initial custom components implementation

- dist/diffhtml.js
- lib/element/make.js
- lib/errors.js
- lib/node/patch.js
- lib/node/sync.js
- lib/patches/process.js
- lib/util/pools.js
- lib/worker/create.js
- lib/worker/source.js
- test/unit/element.js
Workers were never reporting when new elements were created or destroyed
so the UI worker would never know. This patches diffhtml to ensure that
those operations are communicated correctly.
> Adds a ton of documentation and fixes workers

- .jshintrc
- benchmarks/fixtures/dbmonster/randomize.js
- benchmarks/fixtures/reddit/randomize.js
- dist/diffhtml.js
- lib/element/custom.js
- lib/element/get.js
- lib/element/make.js
- lib/index.js
- lib/node/make.js
- lib/node/patch.js
- lib/node/sync.js
- lib/patches/process.js
- lib/transitions.js
- lib/util/entities.js
- lib/util/memory.js
- lib/util/parser.js
- lib/util/pools.js
- lib/worker/create.js
- lib/worker/source.js
- package.json
- test/integration/basics.js
- test/integration/memory.js
- test/integration/outer.js
- test/integration/transitions.js
- test/unit/element.js
- test/unit/transitions.js
Brings in a more formal transitions backend and all tests are passing.
> Backported AMD fixes

- dist/diffhtml.js
- lib/element/custom.js
- lib/element/make.js
- lib/index.js
- lib/node/make.js
- lib/patches/process.js
- lib/transitions.js
- lib/util/memory.js
- lib/util/render.js
- test/integration/custom.js
- test/util/validateMemory.js
- Implemented the `is` attribute.
- Found that attributes weren't properly cleaned up, so added in that
logic.
> Implemented `is` attribute and cleaned up attribute allocations

- .gitattributes
- dist/diffhtml-runtime.js
- dist/diffhtml.js
- karma.conf.js
- lib/index.js
- lib/node/finalize.js
- lib/node/patch.js
- lib/node/transaction.js
- lib/tree/helpers.js
- lib/tree/make.js
- lib/tree/sync.js
- lib/util/cache.js
- lib/util/entities.js
- lib/util/parser.js
- lib/util/pools.js
- test/integration/middleware.js
- test/integration/tagged-template.js
- test/unit/util/parser.js
- test/util/validateMemory.js
This adds in the necessary code to hook up basic middleware into
diffHTML. This will open the door to external tooling to be built around
it.
> Middleware

- dist/diffhtml-runtime.js
- dist/diffhtml.js
- lib/index.js
- test/integration/basics.js
> Remove and migrate the prollyfill

- lib/index.js
Since we are now using them on the site, it makes sense to improve their
descriptor quality.
> Make the JSDoc comments better

- dist/diffhtml-runtime.js
- dist/diffhtml.js
- lib/node/make.js
- lib/node/patch.js
- test/integration/outer.js
> Ensure that entities are decoded in attribute values

- lib/util/parser.js
> Using regex test instead of trim to detect non-whitespace existence

- lib/node/patch.js
- test/integration/inner.js
- test/integration/tagged-template.js
> Test input checked

- lib/node/patch.js
> #97 Fix: diffhtml do not applying checkbox checked

- packages/diffhtml-components/.babelrc
- packages/diffhtml-components/lib/implementations/react-like.js
- packages/diffhtml-components/package.json
- packages/diffhtml-components/test/_setup.js
- packages/diffhtml-components/test/component.js
- packages/diffhtml/.babelrc
- packages/diffhtml/dist/diffhtml-runtime.js
- packages/diffhtml/dist/diffhtml.js
- packages/diffhtml/lib/html.js
- packages/diffhtml/lib/node/create.js
- packages/diffhtml/lib/node/patch.js
- packages/diffhtml/lib/tasks/reconcile-trees.js
- packages/diffhtml/lib/tasks/sync-trees.js
- packages/diffhtml/lib/transaction.js
- packages/diffhtml/lib/transition.js
- packages/diffhtml/lib/tree/create.js
- packages/diffhtml/lib/tree/sync.js
- packages/diffhtml/lib/use.js
- packages/diffhtml/lib/util/caches.js
- packages/diffhtml/lib/util/index.js
- packages/diffhtml/lib/util/memory.js
- packages/diffhtml/rollup.main.config.js
- packages/diffhtml/test/integration/transitions.js
- packages/diffhtml/test/tasks.js
- packages/diffhtml/test/transaction.js
- packages/diffhtml/test/tree.js
- packages/diffhtml/test/use.js
In response to #122 I came up with a naive implementation. However, like @mAAdhaTTah points out there isn't much context around the incoming `vTree` value. Even if we pass the `transaction` as well, that wouldn't be enough to completely replace the recursive `reconcileComponents` function in diffhtml-components.
> Prototype some middleware hooks into the creation process

- packages/diffhtml-website/template.html
Didn't see any style for such long strings. But anyway, I was clicking away in the docs and landed nowhere good. So thought it'd be good to update the links.
> Use new monorepo locations for project plugins

- packages/diffhtml/lib/util/parser.js
- packages/diffhtml/test/html.js
- packages/diffhtml/test/integration/outer.js
- packages/diffhtml/test/util.js
It misses the leading text node.
> Add failing test for text nodes

- packages/babel-preset-diffhtml-imports/index.js
- packages/babel-preset-diffhtml-imports/utils/replace-esm.js
- packages/diffhtml-components/.babelrc
- packages/diffhtml-components/README.md
- packages/diffhtml-components/lib/component.js
- packages/diffhtml-components/lib/shared/get-child-context.js
- packages/diffhtml-components/lib/shared/upgrade-shared-class.js
- packages/diffhtml-components/lib/tasks/react-like-component.js
- packages/diffhtml-components/lib/util/caches.js
- packages/diffhtml-components/test/component.js
- packages/diffhtml-middleware-synthetic-events/index.js
- packages/diffhtml-react-compat/README.md
- packages/diffhtml-react-compat/lib/children.js
- packages/diffhtml-react-compat/lib/index.js
- packages/diffhtml-react-compat/lib/pure-component.js
- packages/diffhtml-react-compat/package.json
- packages/diffhtml-react-compat/rollup.config.js
- packages/diffhtml-static-sync/sync.js
- packages/diffhtml-website/api-browser-es5.js
- packages/diffhtml-website/api-browser.js
- packages/diffhtml/lib/node/patch.js
- packages/diffhtml/lib/transaction.js
- packages/diffhtml/lib/tree/sync.js
- packages/diffhtml/lib/version.js
- packages/diffhtml/test/integration/inner.js
Goals of this PR are to make React compatibility more of a reality. Work has already been started and very little is remaining of overall surface area.
https://facebook.github.io/react/docs/react-api.html
What works today:
- ES6 class component definition
- Rendering JSX
- All lifecycle events
- `setState`
- `forceUpdate`
- `createElement`
- `isValidElement`
- `Children`
What is missing:
> React compatibility

- packages/diffhtml/lib/tree/sync.js
- packages/diffhtml/test/tree.js
> Error if duplicate keys are present

- README.md
- package.json
- packages/diffhtml/package.json
I used [all-contributors](https://github.com/kentcdodds/all-contributors) CLI tool to generate the table. This is more of a first draft for how we should highlight contributors in diffhtml.
I only added my name to the main package.json and the diffhtml package.json, since that's where I've pitched in. Let me know if you have other suggestions.
> Add myself as a contributor

- README.md
- packages/diffhtml-components/lib/util/fake-prop-types.js
- packages/diffhtml-middleware-logger/README.md
- packages/diffhtml-middleware-service-worker/.babelrc
- packages/diffhtml-middleware-service-worker/.gitignore
- packages/diffhtml-middleware-service-worker/README.md
- packages/diffhtml-middleware-service-worker/index.js
- packages/diffhtml-middleware-service-worker/package.json
- packages/diffhtml-middleware-service-worker/rollup.config.js
- packages/diffhtml/lib/index.js
- packages/diffhtml/lib/runtime.js
Since this is part of the PWA story, figured this might be useful.
> Add service worker middleware

- packages/diffhtml/lib/node/patch.js
No change in line length and make a lot of sense as alternatives.
> Remove blacklist whitelist

- packages/diffhtml/lib/util/parse.js
- packages/diffhtml/test/html.js
- packages/diffhtml/test/util.js
Fixes #203 and #205. Greatly improves the attribute pattern matching to follow the spec per #206
> Add tests, update attr regex

- packages/diffhtml/lib/util/parse.js
- packages/diffhtml/test/util.js
This changes the HTML tag regular expression to be more greedy and preserve markup within quotes.
> Support <> in attributes, Closes GH-227

- packages/diffhtml/lib/node/patch.js
- packages/diffhtml/lib/tree/create.js
- packages/diffhtml/lib/util/config.js
- packages/diffhtml/test/tree.js
- packages/diffhtml/test/util.js
Mostly config changes, but also includes updates to patching to simplify and updating types.
> Add unit tests and improve config and other areas

- packages/diffhtml/lib/transaction.js
- packages/diffhtml/lib/util/types.js
Allows disabling MutationObserver
> Add TransactionConfig.disableMutationObserver option

- packages/diffhtml/lib/release.js
- packages/diffhtml/lib/tasks/reconcile-trees.js
- packages/diffhtml/lib/transaction.js
- packages/diffhtml/lib/util/memory.js
Fixes https://github.com/tbranyen/diffhtml/issues/223
> Scrubs attrs and nodes from VTrees when released

- .github/workflows/build-ci.yml
- packages/diffhtml-rust-parser/Cargo.lock
- packages/diffhtml-rust-parser/Cargo.toml
- packages/diffhtml-static-sync/package-lock.json
Will also use this PR to test if latest code is actually passing. I'm seeing it fail locally in unit tests.
> Update rust wasm bindgen tool

- .github/workflows/build-ci.yml
- packages/babel-plugin-transform-diffhtml/babel.config.js
> npm install
