tbranyen/diffhtml

- package.json
Not a very structuring one, but mocha-browser was set as a runtime dependency rather than a dev one.
> Mocha as a development dependency

- README.md
- dist/diffhtml.js
- karma.conf.js
- lib/index.js
- lib/node/make.js
- lib/node/patch.js
- lib/node/sync.js
- lib/patches/process.js
- lib/transitions.js
- lib/util/memory.js
- lib/util/parser.js
- lib/util/pools.js
- lib/util/uuid.js
- lib/worker/source.js
- package.json
- test/integration/memory.js
- test/integration/outer.js
- test/unit/util/parser.js
- test/util/validateMemory.js
This is a collection of miscellaneous work I've been doing. Some stuff floating around in this PR:
- Experimenting with webpack, although not sure it's a huge win since the dist is run through derequire
- Added function names instead of leaving them anonymous
- Swapped out for clearer Array#push instead of using Array#length and assigning directly
- Fixed the bug where transitions were always recursively called into children when only attached and detached should
- Better HTML markup handling, we conform better to the HTML spec, by removing whitespace between `<html></html>` and automatically add in missing `<head></head>` and `<body></body>`.
> Miscellaneous work

- dist/diffhtml.js
- lib/util/memory.js
- lib/util/pools.js
- test/integration/memory.js
- test/util/validateMemory.js
This greatly improves the object pooling performance. No longer do we need to worry about checking `indexOf` on giant arrays.
> Use sets instead of arrays

- dist/diffhtml.js
- examples/transitions/script.html
- karma.conf.js
- lib/index.js
- lib/node/make.js
- lib/patches/process.js
- lib/transitions.js
- lib/util/entities.js
- lib/util/memory.js
- lib/util/parser.js
- lib/util/pools.js
- lib/worker/create.js
- package.json
- test/integration/basics.js
- test/unit/node.js
- test/unit/util/parser.js
- Better support for DocumentFragments and ShadowDOM (tests needed)
- Better support for type extensions (is attribute) (more tests needed)
- Added in a test that shows we cannot support (yet) unescaped HTML inside attribute values
- Added back in code coverage filtering so that tests can run in the browser successfully
- Made changes to ensure object shapes don't change.
> Improves support for ShadowDOM, DocumentFragment, and is attribute for type extensions

- README.md
- dist/diffhtml.js
- lib/element/make.js
- lib/html.js
- lib/node/make.js
- lib/node/patch.js
- lib/node/sync.js
- lib/patches/process.js
- lib/transitions.js
- lib/util/parser.js
- lib/util/pools.js
- test/integration/tagged-template.js
- test/integration/transitions.js
- test/unit/util/parser.js
Adds in a smart algorithm to detect changes between element keys.
> Support for `key` attribute to aid reconcilation

- README.md
Just a note...
Also, what escaping does the tagged template helper use for attributes / innerText/HTML?  I'd like to add that to the docs as well.
> Add note about nested tagged templates and arrays.

- dist/diffhtml.js
- lib/html.js
- lib/util/parser.js
- test/integration/tagged-template.js
- test/unit/util/parser.js
The tagged template helper will now escape any interpolated text values.
This is a safer approach to directly injecting markup. If you wish to
embed raw markup you can use the `html` method directly like so:
``` js
function render() {
let escaped = '<script>window.alert('xss')</script>';
let unescaped = '<center>of attention</center>';
outerHTML(document.body, html`<body>
<p>Escaped: ${escaped}</p>
<p>Unescaped: ${html(unescaped)}</p>
</body>`);
}
render();
```
This patch also addresses two bugs with the parser. Text preceding the
first defined element would be discarded. Another bug was with two
dynamic interpolated values being right next to eachother not
transforming properly.
> Fixes bugs with tagged template helper and escape

- README.md
- dist/diffhtml-runtime.js
- dist/diffhtml.js
- karma.conf.js
- lib/node/finalize.js
- lib/node/transaction.js
- package.json
This adds in the Babel polyfill and removes all the others. I've added a
note to the README for including it in projects that need legacy
support.
I've also changed the util/render.js to be finalize.js under the node/
directory. The function name got updated to getFinalizeCallback which
more accurately summarizes what it does than completeRender.
> Refactor transaction completion + Babel polyfill

- dist/diffhtml.js
- index.html
- lib/util/parser.js
- test/integration/tagged-template.js
If a Text Node appears before any HTML element brackets, we would create
a Text Node with the content, even if the interpolation TOKEN was
present.
> Fix bug with text content and dynamic values

- karma.conf.js
- lib/node/transaction.js
- package.json
- test/integration/basics.js
- test/integration/inner.js
- test/integration/outer.js
Not all browsers behaved with the tests, so I've gone through with
Browserstack and fixed the files that were not valid. Such as creating
an HTML Document without a title (apparently it's a required argument in
some browsers).
Here's the current support chart:
<table>
<thead>
<tr>
<th>IE (9/10/11)
<th>Edge (13)
<th>Firefox (47)
<th>Chrome (51)
<th>Safari (9.1)
<th>Opera (38)
<th>iOS iPhone Safari (9.3)
<th>Android Chrome (50)
<tbody>
<tr>
<td>✗
<td>✓
<td>✓
<td>✓
<td>✓
<td>✓
<td>✓
<td>✓
</table>
I can't get IE 11 to work just yet. I have an undocumented internal
event named `renderComplete`. I may have mentioned it on the website,
but it's definitely going away in it's current form. I'll bring it back
as middleware if anyone needs it.
For instance:
``` javascript
// middleware code
const …
```
> Fixes to the tests to support various browsers

- dist/diffhtml-runtime.js
- dist/diffhtml.js
- lib/node/transaction.js
- lib/util/parser.js
- test/unit/util/parser.js
If you write invalid markup, diffHTML now warns and points you to where the markup is invalid. I opt'd out of throwing since our parser is flexible and that is a plus in some cases. The only thing that is missing is a way to opt-out/disable the warnings.
> Warns on invalid markup terminators

- dist/diffhtml.js
- lib/util/parser.js
- test/unit/util/parser.js
`<pre>` tags can easily nest elements like `<code>`, so I've updated the parser to not treat all `<pre>` contents as text. I have updated the `<code>` element to treat all contents as text though.
I've also updated the parser to interpolate dynamic values into these blocks.
Basically:
``` js
const someCoolVariable = "Hello world";
```
``` html
<pre>
<code>
${someCoolVariable}
</code>
</pre>
```
Was rendering out as:
``` html
<pre>
&lt;code&gt;
__DIFFHTML__
&lt;/code&gt;
</pre>
```
This fixes it to produce the correct output:
``` html
<pre>
<code>
Hello world
</code>
</pre>
```
> Fixes parser issue with pre code blocks

- lib/node/finalize.js
- test/integration/transitions.js
This event was undocumented and is now removed. Makes it easier to test
with various browsers.
> Refactor tests to not use renderComplete event

- dist/diffhtml-runtime.js
- dist/diffhtml.js
- lib/util/tagged-template.js
- test/unit/util/tagged-template.js
The isProp regular expression was insufficient as it only checked the
preceding string, and if you had multiple values, the second preceding
string would be a single space (attribute value delimiter). Now we run
the regex starting from the end and working its way back to determine if
we're in an attribute/property.
> Fixes handling of interpolated attributes

- packages/diffhtml-middleware-inline-transitions/README.md
- packages/diffhtml-middleware-inline-transitions/index.js
- packages/diffhtml-middleware-inline-transitions/test/basics.js
- packages/diffhtml-middleware-inline-transitions/test/regressions.js
This commit updates the README to flatten all event names to lower case,
but does not require it. It updates the signature of the event lookup to
be: 'onattached' from 'attached', this indicates its more of an event
that is frequently called. Since none of these events currently
collide with browser events it shouldn't be an issue. Although if they
ever do, I'm sure this project may be long dead by then...
> Lowercases all event names, normalizes to 'on*'

- packages/diffhtml-components/package.json
- packages/diffhtml-shared-internals/package.json
- packages/diffhtml/package.json
`module` is used by rollup; `jsnext:main` is what it used to use.
> Add module & jsnext:main

- packages/diffhtml-components/test/component.js
- packages/diffhtml-shared-internals/lib/make-measure.js
- packages/diffhtml-shared-internals/lib/parser.js
- packages/diffhtml-shared-internals/lib/pool.js
- packages/diffhtml-shared-internals/lib/process.js
Some of these are default exports, which aren't getting reexported
properly from the shared-internals module.
> Reexport default exports from shared-internals

- packages/diffhtml/lib/util/process.js
- packages/diffhtml/test/util.js
diffHTML core doesn't pave over the process object, but the components repo pulls in this object and paves it over globally.
> Fix accidentally paving over the process object

- packages/diffhtml/lib/index.js
- packages/diffhtml/lib/runtime.js
- packages/diffhtml/lib/transaction.js
This allows middleware to access a task without needing to know what
index the task is located at.
> Add tasks keyed by name to Internals

- packages/babel-plugin-transform-diffhtml/dist/index.js
- packages/babel-plugin-transform-diffhtml/src/index.js
- packages/diffhtml-components/lib/tasks/react-like-component.js
- packages/diffhtml-components/lib/tasks/web-component.js
- packages/diffhtml-components/lib/web-component.js
- packages/diffhtml-components/test/component.js
- packages/diffhtml-components/test/web-component.js
- packages/diffhtml/lib/node/create.js
- packages/diffhtml/lib/tree/create.js
- packages/diffhtml/lib/util/internals.js
- packages/diffhtml/lib/util/svg.js
- packages/diffhtml/rollup.runtime.config.js
- packages/diffhtml/test/util.js
- Better support for `props.children`. Fixes issues with multiple top level elements during a component render.
- Removed the unnecessary SVG file now
- Top level renders are fully supported as well as returning arrays from renders
- Babel transpiler works! Cool trick is to configure it with:
``` json
{
"plugins": [
["transform-diffhtml", { "createTree": "html" }]
]
}
```
And then make sure you're loading the `runtime` build. This will allow you to write code like:
``` js
// Alias diffhtml to diffhtml/runtime or dist/es/runtime or dist/cjs/runtime or dist/diffhtml-runtime
import { innerHTML, html } from 'diffhtml';
function render() {
return html`
<div>Hello world</div>
`;
}
innerHTML(document.body, render());
```
And have it neatly transpiled without needing to import `diff` in its …
> Updates to Component/Web Component

- packages/babel-plugin-transform-diffhtml/dist/index.js
- packages/babel-plugin-transform-diffhtml/src/index.js
- packages/diffhtml-components/lib/component.js
- packages/diffhtml-components/lib/tasks/react-like-component.js
- packages/diffhtml-components/lib/web-component.js
- packages/diffhtml-static-sync/README.md
- packages/diffhtml-static-sync/index.js
- packages/diffhtml-static-sync/lib/socket.js
- packages/diffhtml-static-sync/lib/util/client-script.js
- packages/diffhtml-static-sync/lib/watch.js
- packages/diffhtml-static-sync/package.json
- packages/diffhtml-static-sync/sync.js
- packages/diffhtml/lib/node/patch.js
- packages/diffhtml/lib/tasks/patch-node.js
- packages/diffhtml/lib/tree/sync.js
- packages/diffhtml/package.json
- Added verbose logging
- Retry logic every 2 seconds
- Release the documentElement before patching, forcing a complete memory dump and recreation. While diffHTML should handle this stuff just fine, this seems like a safer way to handle potentially busted markup.
- Maintain list of sockets instead of just the first one
- LiveReload CSS
> Improve static sync reliability

- packages/babel-plugin-transform-diffhtml/dist/index.js
- packages/babel-plugin-transform-diffhtml/src/index.js
- packages/diffhtml-components/lib/index.js
- packages/diffhtml-components/lib/tasks/react-like-component.js
- packages/diffhtml-components/lib/util/caches.js
- packages/diffhtml-components/lib/util/internals.js
- packages/diffhtml-components/lib/web-component.js
- packages/diffhtml-static-sync/sync.js
- packages/diffhtml/lib/node/create.js
When creating new elements I found that SVG foreignObject is case
sensitive. We need to keep this in mind when creating elements.
> Expose Component internals, respect rawNodeName

- packages/diffhtml/lib/util/parse.js
- packages/diffhtml/test/util.js
This should parse the hard return as a child of the `code` element,
but instead produces a vTree with no children.
Currently just a test case.
> Add test case for parser bug

- packages/diffhtml/lib/tree/sync.js
- packages/diffhtml/test/tree.js
This is a reversion of the change found in
e282dbc78e51bb12d8e39ecc4db63d733f084cf0 and a test to ensure
the prevention of future regressions. [See comments.](https://github.com/tbranyen/diffhtml/commit/e282dbc78e51bb12d8e39ecc4db63d733f084cf0#commitcomment-23617776)
> Fix syncTrees from generating too many patches

- packages/diffhtml/lib/tasks/reconcile-trees.js
- packages/diffhtml/lib/tasks/should-update.js
- packages/diffhtml/test/integration/inner.js
This fixes a reported issue where an appended DOM node was not removed after a subsequent render.
> Fix fragment sync

- packages/diffhtml/lib/util/parse.js
Now allows html attributes that use colons(e.g. v-bind:variable="x") to be correctly parsed
> Fixed regex for special cases

- packages/diffhtml-components/lib/web-component.js
- packages/diffhtml-render-to-string/README.md
- packages/diffhtml-render-to-string/index.js
- packages/diffhtml-render-to-string/package.json
- packages/diffhtml-render-to-string/test/index.js
- packages/diffhtml-website/build/generate.js
- packages/diffhtml/lib/node/create.js
I've wanted to update this module for a long time and finally got some inspiration to complete it. Before render-to-string was a hack that didn't support middleware (such as components) and instead tried to support the minimal amount of features possible.
Now it's a GIANT hack, but leverages all public APIs to support middleware and more! I refactored the tests to pull components from diffhtml-components to show a proof-of-concept.
I will continue adding tests in here so that behavior is understood.
> Greatly improve render-to-string

- packages/diffhtml-middleware-linter/.babelrc
- packages/diffhtml-middleware-linter/.gitignore
- packages/diffhtml-middleware-linter/README.md
- packages/diffhtml-middleware-linter/index.js
- packages/diffhtml-middleware-linter/package.json
- packages/diffhtml-middleware-linter/rollup.config.js
- packages/diffhtml-middleware-linter/test.html
Allows validating HTML input using HTMLHint (https://github.com/htmlhint/HTMLHint) rules.
Usage:
```js
import { use, innerHTML } from 'diffhtml';
import linter from 'diffhtml-middleware-linter';
// Default rules
use(linter());
innerHTML(document.body, `
<a HREF="failure" />
`);
```
> Initial work on HTML linter based off htmlhint

- packages/diffhtml/lib/node/patch.js
- packages/diffhtml/lib/tasks/patch-node.js
- packages/diffhtml/lib/tasks/sync-trees.js
- packages/diffhtml/lib/transaction.js
- packages/diffhtml/lib/tree/sync.js
- packages/diffhtml/test/integration/svg.js
Prior to this commit, SVG would only work if rendered directly from the
top, like: `diff.innerHTML(document.body, '<svg></svg>');` and not when
diffing or creating within an existing document.
This corrects the behavior by determining the correct type during
synchronization, applying this VTree reference to an `svgElements` set,
and then referencing this when creating elements in the patch phase.
This should not incur any memory overhead or significant processing and
keeps our VTree shape lean, and filesize low by not including a list of
all SVG elements.
Fixes GH #185
> Resolve namespace issues when creating SVG element

- README.md
- packages/diffhtml-components/lib/shared/middleware.js
- packages/diffhtml-website/pages/api.md
- packages/diffhtml/lib/tree/sync.js
- packages/diffhtml/test/integration/inner.js
- packages/diffhtml/test/tree.js
- packages/diffhtml/test/use.js
This change improves synchronization to always account for all elements in either the old or new set. Before we only cared about the new set which short circuits a lot of logic. This comes at a negative when you have elements added by third parties and want to ensure that diffHTML can seamlessly render around them. This allows us to call the `SyncTreeHook` for every old node. This is beneficial in the case where you've added nodes without diffHTML (possibly by a third party) and would like a chance to tell diffHTML to ignore them.
To ignore diffing an element you can use the following new code pattern:
```js
import { innerHTML, use, Internals } from 'diffhtml';
use({
syncTreeHook(oldTree) {
// Inspect the VTree for attributes or nodeName and return false to tell
// diffHTML to completely …
```
> Greatly improve handling of untracked elements

- packages/diffhtml/lib/util/parse.js
- packages/diffhtml/test/util.js
As noted in #209, diffHTML incorrect parses code as an element that should not have it's children parsed as HTML, like you would find with a script or style tag. This is incorrect behavior and is corrected with this changeset.
> Remove code from block elements, fixes GH-209

- packages/diffhtml/lib/inner-html.js
- packages/diffhtml/lib/release.js
- packages/diffhtml/lib/tasks/parse-new-tree.js
- packages/diffhtml/lib/tasks/patch-node.js
- packages/diffhtml/lib/tasks/reconcile-trees.js
- packages/diffhtml/lib/tasks/schedule.js
- packages/diffhtml/lib/tasks/should-update.js
- packages/diffhtml/lib/tasks/sync-trees.js
- packages/diffhtml/lib/transaction.js
- packages/diffhtml/lib/util/make-measure.js
- packages/diffhtml/lib/util/types.js
- packages/diffhtml/test/tasks.js
- packages/diffhtml/test/transaction.js
- packages/diffhtml/test/util.js
- Renamed domNode to mount
- Renamed options to config
- Keep track of marks via transaction id increment
> Fix timing marks, update internal variables Close GH-198

- packages/diffhtml/lib/release.js
- packages/diffhtml/lib/tasks/reconcile-trees.js
- packages/diffhtml/lib/transaction.js
- packages/diffhtml/lib/util/types.js
- packages/diffhtml/package.json
- packages/diffhtml/test/tasks.js
- packages/diffhtml/test/transaction.js
- packages/diffhtml/test/use.js
This fixes #217 by using a MutationObserver to detect whenever the DOM changes and becomes dirty after a render. This appears to the best way to reliably know if the DOM has changed under the element. `outerHTML` is not sufficient as markup may be identical, but the Nodes have changed.
> Fix issues with external markup changes

- packages/diffhtml-website/components/layout.js
Been seeing performance issues on diffhtml.org lately, which might be around the nginx rules. Testing out loading static assets directly from github.io.
> Point to specific version of assets on github

- packages/babel-plugin-transform-diffhtml/lib/index.js
- packages/diffhtml/lib/to-string.js
- packages/diffhtml/lib/util/parse.js
- packages/diffhtml/test/html.js
- packages/diffhtml/test/to-string.js
- packages/diffhtml/test/util.js
Fixes issue GH-242
Supports better parsing around attributes. Instead of simply mirroring keys like disabled to serve as the value, instead determine if a `true` value is more appropriate.
> Fix bool attr parsing

- packages/diffhtml/lib/node/patch.js
This brings https://github.com/tbranyen/diffhtml/issues/242 to conclusion.
With input:
```html
<video controls></video>
```
we get
before #242:
```html
<video controls="controls"></video>
```
after #242:
```html
<video controls="true"></video>
```
after this pull request:
```html
<video controls></video>
```
---
<details><summary>Intentional/explicit <code>"true"</code> as string in the input, works the same, as desired, before/after this pull request.</summary>
input:
```html
<a title="true">x</a>
```
after this pull request:
```html
<a title="true">x</a>
```
</details>
> set boolean attributes as '' (not 'true')

- packages/diffhtml/lib/transaction.js
- packages/diffhtml/lib/util/types.js
- packages/diffhtml/test/transaction.js
Takes advice from #249 and creates a new script element and mirrors the existing contents and attributes/properties into it. Should be functionally equivalent to using `domNode.cloneNode`. This fixes a problem in Firefox where changing a scripts type attribute has no effect (once added to the dom), unlike in Chrome.
> Fixes issues with scripts in Firefox

- packages/diffhtml-components/.mocharc.json
- packages/diffhtml-components/lib/component.js
- packages/diffhtml-components/lib/util/symbols.js
- packages/diffhtml-components/test/integration/component.js
- packages/diffhtml/lib/node/patch.js
- packages/diffhtml/lib/tree/sync.js
- packages/diffhtml/lib/util/symbols.js
This is helps with workers and servers that do not have access to the DOM. This channels all operations over the pipeline used for the patch phase. This is an array of operations that can be serialized over web workers and sockets.
Helps with:
- Tracking all DOM operations for single and multiple top level elements
- Channeling 100% of component operations through the transaction pipeline in a standard way
> Use patch logic for component render

- packages/diffhtml-components/lib/create-side-effect.js
- packages/diffhtml-components/lib/create-state.js
- packages/diffhtml-components/lib/index.js
- packages/diffhtml-components/lib/middleware.js
- packages/diffhtml-components/lib/once-ended.js
- packages/diffhtml-components/lib/render-component.js
- packages/diffhtml-components/lib/util/types.js
- packages/diffhtml-components/test/integration/hooks.js
- packages/diffhtml-components/test/util/validate-caches.js
- packages/diffhtml-website/pages/components.md
This introduces `createSideEffect` which matches `useEffect` from React. It is currently incomplete, but in a somewhat usable form. I need to do some refactoring around how/when we call lifecycle methods as the current approach isn't entirely accurate.
Right now we call `componentWillUnmount` after patching, which is not right, it should happen before the element actually unmounts.
> Implements createSideEffect

- packages/diffhtml/lib/html.js
- packages/diffhtml/lib/node/patch.js
- packages/diffhtml/test/integration/basics.js
Closes GH-261, allows patching to more safely remove attributes that have been designed to not allow the `delete` operator on them.
> Supports set vs remove attribute

- packages/diffhtml/lib/util/config.js
> Protect process.env access by checking if process exists first

- packages/diffhtml-components/lib/util/process.js
- packages/diffhtml/lib/node/create.js
- packages/diffhtml/lib/tasks/sync-trees.js
- packages/diffhtml/lib/transaction.js
- packages/diffhtml/lib/transition.js
- packages/diffhtml/lib/tree/sync.js
- packages/diffhtml/lib/use.js
- packages/diffhtml/lib/util/config.js
- packages/diffhtml/lib/util/internals.js
- packages/diffhtml/lib/util/parse.js
- packages/diffhtml/package-lock.json
- packages/diffhtml/package.json
- packages/diffhtml/rollup.lite.config.js
- packages/diffhtml/rollup.main.config.js
This fixes GH-268. Webpack has issues with the process variable and by
renaming the internal usage we can ensure that it points to our
representation and not the external one.
> Rename process to internalProcess

- packages/babel-plugin-transform-diffhtml/lib/index.js
- packages/diffhtml-components/lib/render-component.js
- packages/diffhtml-components/test/component.js
- packages/diffhtml-components/test/integration/web-component.js
- packages/diffhtml-middleware-linter/lib/index.js
- packages/diffhtml-static-sync/sync.js
- packages/diffhtml-website/components/layout.js
- packages/diffhtml-website/config.json
- packages/diffhtml-website/pages/api.md
- packages/diffhtml-website/pages/index.md
- packages/diffhtml-website/pages/parser.md
- packages/diffhtml-website/public/styles/index.css
- packages/diffhtml/lib/html.js
- packages/diffhtml/lib/node/create.js
- packages/diffhtml/lib/tasks/parse-new-tree.js
- packages/diffhtml/lib/tree/create.js
- packages/diffhtml/lib/util/config.js
- packages/diffhtml/lib/util/parse.js
- packages/diffhtml/lib/util/symbols.js
- packages/diffhtml/lib/util/types.js
- packages/diffhtml/test/html.js
- packages/diffhtml/test/integration/basics.js
- packages/diffhtml/test/integration/inner.js
- packages/diffhtml/test/integration/outer.js
- packages/diffhtml/test/integration/tagged-template.js
- packages/diffhtml/test/to-string.js
- packages/diffhtml/test/use.js
- packages/diffhtml/test/util.js
**Status:** In Progress
**Goals:**
The primary motivations of the rewrite are to fix known compatibility bugs, support comments completely (instead of skipping them), improve support for middleware, and greatly improve memory usage and performance. The way the new parser works is by breaking down the HTML using global regexes that have their lastIndex reset on each loop. No copies or references of the input HTML are made. The VTree hierarchy is built up as the markup is crawled. This iteration of the parser is to help ship 1.0. Using regex's like this is prone to errors and not ideal to parse real HTML, but using any known alternatives will incur significant filesize impact, not work in Node, or be overkill for what is needed, which is basically HTML/XML/SVG -> JSON.
**Tasks:**
**Future …
> HTML Parser Rewrite

- packages/diffhtml/lib/util/parse.js
- packages/diffhtml/test/use.js
In the new parser createTree was called with only a tag name and not the attributes or childNodes. This PR fixes the new parser to wait until the element is closed before calling createTree. This work uncovered some inconsistencies and improved the parser by closing out the pointer and resetting to the parent in a function.
> Call createTree on parser close, not open

- packages/diffhtml/lib/util/memory.js
- packages/diffhtml/lib/util/pool.js
- packages/diffhtml/test/util.js
When VTree were getting unprotected, they were being recirculated immediately. Instead they are now kept in allocation, until GC kicks in. Adds tests to validate the expected behavior.
> Fixes allocation for better GC

- packages/diffhtml/lib/html.js
- packages/diffhtml/lib/inner-html.js
- packages/diffhtml/lib/node/create.js
- packages/diffhtml/lib/node/patch.js
- packages/diffhtml/lib/outer-html.js
- packages/diffhtml/lib/release.js
- packages/diffhtml/lib/tasks/end-as-transaction.js
- packages/diffhtml/lib/tasks/parse-new-tree.js
- packages/diffhtml/lib/tasks/patch-node.js
- packages/diffhtml/lib/tasks/reconcile-trees.js
- packages/diffhtml/lib/tasks/should-update.js
- packages/diffhtml/lib/tasks/sync-trees.js
- packages/diffhtml/lib/to-string.js
- packages/diffhtml/lib/transaction.js
- packages/diffhtml/lib/tree/create.js
- packages/diffhtml/lib/tree/sync.js
- packages/diffhtml/lib/use.js
- packages/diffhtml/lib/util/config.js
- packages/diffhtml/lib/util/internals.js
- packages/diffhtml/lib/util/parse.js
- packages/diffhtml/lib/util/pool.js
- packages/diffhtml/lib/util/process.js
- packages/diffhtml/lib/util/types.js
- packages/diffhtml/test/util/create-supplemental.js
By aliases objects to types we were able to use native ESM to get type access. Since the type system has zero runtime benefit, I've migrated all imports into JSDoc import comments and assigned local typedefs into each module scope.
This gets rid of circular dependency warnings and should be easier to read.
> Removes type aliases

- packages/diffhtml/lib/tasks/patch-node.js
- packages/diffhtml/lib/transaction.js
- packages/diffhtml/test/integration/basics.js
A regression was reported by @nbianca where mutations to markup were not reflected internally. I had set `isDirty` to true in the [mutationobserver callback](https://github.com/tbranyen/diffhtml/pull/219/files#diff-a3690839a2f001661f7ed8f74ba455c44f0a0b9d100b5c7066f1b722cc3b6522R141). That was then removed when I added better support for [component top level rendering](https://github.com/tbranyen/diffhtml/commit/c9cb93688f194ba5f620550a0c5f657ded0ea3b9#diff-a3690839a2f001661f7ed8f74ba455c44f0a0b9d100b5c7066f1b722cc3b6522R144).
To fix this, I'm simply purging the mutationobserver records after every render since we only care about mutations when we aren't rendering (due to its synchronous nature).
> Fix for mutation observer isDirty
